Test release (#30)
chore: test and debug CD

Co-authored-by: Baptiste GELLATO <baptiste.gellato-ext@ixxitechside.com>

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -8,7 +8,7 @@ permissions:
   contents: write
   issues: write
   pull-requests: write
-  
+
 jobs:
   build-and-publish:
     runs-on: ubuntu-latest
@@ -36,8 +36,26 @@ jobs:
       - name: Build library
         run: npm run build
 
+      - name: Force NPM config
+        run: |
+          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
+          npm whoami || echo "❌ npm whoami failed"
+        env:
+          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
+          NODE_AUTH_TOKEN: ""
+          NPM_CONFIG_USERCONFIG: .npmrc
+
       - name: Semantic Release
-        run: npx semantic-release --dry-run
+        run: |
+          if [ "$GITHUB_REF_NAME" = "main" ]; then
+            echo "🔁 Running semantic-release in production mode"
+            npx semantic-release
+          else
+            echo "🧪 Running semantic-release in dry-run mode on branch: $GITHUB_REF_NAME"
+            npx semantic-release --dry-run
+          fi
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
+          NODE_AUTH_TOKEN: ""
+          NPM_CONFIG_USERCONFIG: .npmrc
